"""add safety_stock

Revision ID: f402c58b719c
Revises: 7755e3fb455c
Create Date: 2026-09-17 20:20:56.706275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f402c58b719c'
down_revision: Union[str, Sequence[str], None] = '7755e3fb455c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('safety_stock', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'safety_stock')
    # ### end Alembic commands ###
